In [1]:
import numpy as np

In [2]:
A = np.array([
            [4, -3, 1],
            [2, 1, 3],
            [-1, 2, -5]
             ], dtype = np.dtype(float))
b = np.array([-10,0,17], dtype = np.dtype(float))

In [3]:
b

array([-10.,   0.,  17.])

In [4]:
b.shape

(3,)

In [5]:
x = np.linalg.solve(A,b)

In [6]:
x

array([ 1.,  4., -2.])

In [7]:
np.linalg.det(A)

-60.000000000000036

In [8]:
A_system = np.hstack((A,b.reshape(3,1)))

In [9]:
A_system

array([[  4.,  -3.,   1., -10.],
       [  2.,   1.,   3.,   0.],
       [ -1.,   2.,  -5.,  17.]])

In [10]:
def multiply_row(M, row_num, row_num_multiple):
    M_new = M.copy()
    M_new[row_num] = M[row_num] * row_num_multiple
    return M_new

In [11]:
multiply_row(A_system, 1, -5)

array([[  4.,  -3.,   1., -10.],
       [-10.,  -5., -15.,  -0.],
       [ -1.,   2.,  -5.,  17.]])

In [37]:
def add_rows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] =( M_new[
        row_num_1] * row_num_1_multiple ) + M_new[row_num_2]
    return M_new
    

In [38]:
def swap_rows(M,row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1,row_num_2]] = M_new[[row_num_2,row_num_1]]
    return M_new

In [39]:
SwapRows(A_system,0,1)

array([[  2.,   1.,   3.,   0.],
       [  4.,  -3.,   1., -10.],
       [ -1.,   2.,  -5.,  17.]])

In [40]:
A_new = swap_rows(A_system,0,2)
A_new

array([[ -1.,   2.,  -5.,  17.],
       [  2.,   1.,   3.,   0.],
       [  4.,  -3.,   1., -10.]])

In [41]:
A_new = add_rows(A_new, 0,1,2)

A_new

array([[ -1.,   2.,  -5.,  17.],
       [  0.,   5.,  -7.,  34.],
       [  4.,  -3.,   1., -10.]])

In [42]:
A_new = add_rows(A_new, 0,2,4)
A_new

array([[ -1.,   2.,  -5.,  17.],
       [  0.,   5.,  -7.,  34.],
       [  0.,   5., -19.,  58.]])

In [44]:
!gh repo create maths --public

✓ Created repository bellicosi-in/maths on GitHub


A new release of gh is available: 2.32.1 → 2.44.1
https://github.com/cli/cli/releases/tag/v2.44.1



In [48]:
!git add README.md
!echo "### using numpy to learn linear algebra" > README.md

In [47]:
!git init

Initialized empty Git repository in /Users/priyanshukumar/Desktop/maths_py/.git/


In [49]:
!git remote add origin https://github.com/bellicosi-in/maths.git

In [50]:
!git branch -m main

In [52]:
!touch .gitignore

In [ ]:
!echo 